//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCalendar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<byte> MeetingViaId { get; set; }
        public Nullable<byte> MeetingDoneId { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public string Whom { get; set; }
        public string Description { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual MeetingDone MeetingDone { get; set; }
        public virtual MeetingVia MeetingVia { get; set; }
        public virtual Users Users { get; set; }
    }
}
